services:

  postgres:
    image: postgres
    restart: unless-stopped
    networks:
      - tasks-postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: 1q2w3e4r
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:1q2w3e4r@postgres:5432/postgres?schema=tasks

networks:
  tasks-postgres:
    driver: bridge


