version: '3.8'
services:
  postgres:
    image: postgres
    healthcheck:
      test: "exit 0"
    restart: unless-stopped
    networks:
      - tasks-postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: 1q2w3e4r
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "3000:3000"
    networks:
      - tasks-postgres
    depends_on:
      postgres:
          condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:1q2w3e4r@postgres:5432/postgres?schema=tasks
      SECRET: 0123456789ABCDEF0123456789ABCDEF

networks:
  tasks-postgres:
    driver: bridge
